### PR TITLE
Fix some bug when scrollView scroll back and forth

### PR DESCRIPTION
**Pull request by sgxiang**

### CODE REVIEW

**Comment by michaelbabiy** [comment]
I am not sure what bug this fixes. I am going to close this request. Thank you.

**Comment by sgxiang** [comment]
@michaelbabiy https://www.youtube.com/watch?v=wKM62oeW3J4&feature=youtu.be

**Comment by michaelbabiy** [comment]
Unfortunately I cannot reproduce it... Ill take a closer look a bit later. Thank you though!

**Comment by sgxiang** [comment]
You can make scrollView fast to rolling back and forth a few times

**Comment by michaelbabiy** [comment]
Yes, I tried that. It seems to work fine on the device. Maybe simulator is a different story. Regardless, I doubt people will be scrolling back and forth "super fast" nonstop. I'll still investigate it when I get some time this week. But your help and initiative is really appreciated. Thank you.

**Pull request closed without merging**
